export const jobPostings = [
    {
        id: 1,
        title: "Software Engineer",
        totalApplicants: 125,
        successRate: 0.65,
        scheduledInterviews: 45,
        openPositions: 3,
        status: "Active",
    },
    {
        id: 2,
        title: "Product Manager",
        totalApplicants: 82,
        successRate: 0.72,
        scheduledInterviews: 28,
        openPositions: 2,
        status: "Active",
    },
    {
        id: 3,
        title: "UI/UX Designer",
        totalApplicants: 93,
        successRate: 0.58,
        scheduledInterviews: 35,
        openPositions: 1,
        status: "Closed",
    },
    {
        id: 4,
        title: "Data Analyst",
        totalApplicants: 68,
        successRate: 0.79,
        scheduledInterviews: 22,
        openPositions: 2,
        status: "Active",
    },
    {
        id: 5,
        title: "Marketing Coordinator",
        totalApplicants: 54,
        successRate: 0.63,
        scheduledInterviews: 18,
        openPositions: 1,
        status: "Closed",
    },
];
